/*
 * Copyright 2012 Bangkok Project Team, GRIDSOLUT GmbH + Co.KG, and
 * University of Stuttgart (Institute of Architecture of Application Systems)
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.16 at 09:35:20 PM CEST 
//


package org.oasis_open.docs.ns.bpel4people.ws_humantask._200803;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.oasis_open.docs.ns.bpel4people.ws_humantask._200803 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PeopleAssignments_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "peopleAssignments");
    private final static QName _Import_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "import");
    private final static QName _Notification_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "notification");
    private final static QName _HumanInteractions_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "humanInteractions");
    private final static QName _Priority_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "priority");
    private final static QName _TaskInitiator_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "taskInitiator");
    private final static QName _Notifications_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "notifications");
    private final static QName _GenericHumanRole_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "genericHumanRole");
    private final static QName _Tasks_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "tasks");
    private final static QName _PotentialOwners_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "potentialOwners");
    private final static QName _BusinessAdministrators_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "businessAdministrators");
    private final static QName _LeanTask_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "leanTask");
    private final static QName _LogicalPeopleGroups_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "logicalPeopleGroups");
    private final static QName _ExcludedOwners_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "excludedOwners");
    private final static QName _Task_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "task");
    private final static QName _TaskStakeholders_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "taskStakeholders");
    private final static QName _Recipients_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "recipients");
    private final static QName _TExtensibleMixedContentElementsDocumentation_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", "documentation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis_open.docs.ns.bpel4people.ws_humantask._200803
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TGenericHumanRoleAssignment }
     */
    public TGenericHumanRoleAssignment createTGenericHumanRoleAssignment() {
        return new TGenericHumanRoleAssignment();
    }

    /**
     * Create an instance of {@link TGenericHumanRoleAssignmentBase }
     */
    public TGenericHumanRoleAssignmentBase createTGenericHumanRoleAssignmentBase() {
        return new TGenericHumanRoleAssignmentBase();
    }

    /**
     * Create an instance of {@link TTask }
     */
    public TTask createTTask() {
        return new TTask();
    }

    /**
     * Create an instance of {@link TLeanTask }
     */
    public TLeanTask createTLeanTask() {
        return new TLeanTask();
    }

    /**
     * Create an instance of {@link TPotentialOwnerAssignment }
     */
    public TPotentialOwnerAssignment createTPotentialOwnerAssignment() {
        return new TPotentialOwnerAssignment();
    }

    /**
     * Create an instance of {@link TTasks }
     */
    public TTasks createTTasks() {
        return new TTasks();
    }

    /**
     * Create an instance of {@link TLogicalPeopleGroups }
     */
    public TLogicalPeopleGroups createTLogicalPeopleGroups() {
        return new TLogicalPeopleGroups();
    }

    /**
     * Create an instance of {@link TNotifications }
     */
    public TNotifications createTNotifications() {
        return new TNotifications();
    }

    /**
     * Create an instance of {@link TPriorityExpr }
     */
    public TPriorityExpr createTPriorityExpr() {
        return new TPriorityExpr();
    }

    /**
     * Create an instance of {@link TNotification }
     */
    public TNotification createTNotification() {
        return new TNotification();
    }

    /**
     * Create an instance of {@link TImport }
     */
    public TImport createTImport() {
        return new TImport();
    }

    /**
     * Create an instance of {@link TPeopleAssignments }
     */
    public TPeopleAssignments createTPeopleAssignments() {
        return new TPeopleAssignments();
    }

    /**
     * Create an instance of {@link THumanInteractions }
     */
    public THumanInteractions createTHumanInteractions() {
        return new THumanInteractions();
    }

    /**
     * Create an instance of {@link TFrom }
     */
    public TFrom createTFrom() {
        return new TFrom();
    }

    /**
     * Create an instance of {@link TAggregate }
     */
    public TAggregate createTAggregate() {
        return new TAggregate();
    }

    /**
     * Create an instance of {@link TMessageSchema }
     */
    public TMessageSchema createTMessageSchema() {
        return new TMessageSchema();
    }

    /**
     * Create an instance of {@link TToPart }
     */
    public TToPart createTToPart() {
        return new TToPart();
    }

    /**
     * Create an instance of {@link TText }
     */
    public TText createTText() {
        return new TText();
    }

    /**
     * Create an instance of {@link TComposition }
     */
    public TComposition createTComposition() {
        return new TComposition();
    }

    /**
     * Create an instance of {@link TParameter }
     */
    public TParameter createTParameter() {
        return new TParameter();
    }

    /**
     * Create an instance of {@link TExtension }
     */
    public TExtension createTExtension() {
        return new TExtension();
    }

    /**
     * Create an instance of {@link TRendering }
     */
    public TRendering createTRendering() {
        return new TRendering();
    }

    /**
     * Create an instance of {@link TReassignment }
     */
    public TReassignment createTReassignment() {
        return new TReassignment();
    }

    /**
     * Create an instance of {@link TMessageField }
     */
    public TMessageField createTMessageField() {
        return new TMessageField();
    }

    /**
     * Create an instance of {@link TDeadlines }
     */
    public TDeadlines createTDeadlines() {
        return new TDeadlines();
    }

    /**
     * Create an instance of {@link TCopy }
     */
    public TCopy createTCopy() {
        return new TCopy();
    }

    /**
     * Create an instance of {@link TDocumentation }
     */
    public TDocumentation createTDocumentation() {
        return new TDocumentation();
    }

    /**
     * Create an instance of {@link TDurationExpr }
     */
    public TDurationExpr createTDurationExpr() {
        return new TDurationExpr();
    }

    /**
     * Create an instance of {@link TNotificationInterface }
     */
    public TNotificationInterface createTNotificationInterface() {
        return new TNotificationInterface();
    }

    /**
     * Create an instance of {@link TCompletion }
     */
    public TCompletion createTCompletion() {
        return new TCompletion();
    }

    /**
     * Create an instance of {@link TExtensibleElements }
     */
    public TExtensibleElements createTExtensibleElements() {
        return new TExtensibleElements();
    }

    /**
     * Create an instance of {@link TTaskInterface }
     */
    public TTaskInterface createTTaskInterface() {
        return new TTaskInterface();
    }

    /**
     * Create an instance of {@link TExtensions }
     */
    public TExtensions createTExtensions() {
        return new TExtensions();
    }

    /**
     * Create an instance of {@link TPresentationParameter }
     */
    public TPresentationParameter createTPresentationParameter() {
        return new TPresentationParameter();
    }

    /**
     * Create an instance of {@link TPresentationElements }
     */
    public TPresentationElements createTPresentationElements() {
        return new TPresentationElements();
    }

    /**
     * Create an instance of {@link TDeadlineExpr }
     */
    public TDeadlineExpr createTDeadlineExpr() {
        return new TDeadlineExpr();
    }

    /**
     * Create an instance of {@link TDescription }
     */
    public TDescription createTDescription() {
        return new TDescription();
    }

    /**
     * Create an instance of {@link TQuery }
     */
    public TQuery createTQuery() {
        return new TQuery();
    }

    /**
     * Create an instance of {@link TLocalNotification }
     */
    public TLocalNotification createTLocalNotification() {
        return new TLocalNotification();
    }

    /**
     * Create an instance of {@link TLogicalPeopleGroup }
     */
    public TLogicalPeopleGroup createTLogicalPeopleGroup() {
        return new TLogicalPeopleGroup();
    }

    /**
     * Create an instance of {@link TSubtask }
     */
    public TSubtask createTSubtask() {
        return new TSubtask();
    }

    /**
     * Create an instance of {@link TExtensibleMixedContentElements }
     */
    public TExtensibleMixedContentElements createTExtensibleMixedContentElements() {
        return new TExtensibleMixedContentElements();
    }

    /**
     * Create an instance of {@link TSequence }
     */
    public TSequence createTSequence() {
        return new TSequence();
    }

    /**
     * Create an instance of {@link TExpression }
     */
    public TExpression createTExpression() {
        return new TExpression();
    }

    /**
     * Create an instance of {@link TToParts }
     */
    public TToParts createTToParts() {
        return new TToParts();
    }

    /**
     * Create an instance of {@link TResult }
     */
    public TResult createTResult() {
        return new TResult();
    }

    /**
     * Create an instance of {@link TRenderings }
     */
    public TRenderings createTRenderings() {
        return new TRenderings();
    }

    /**
     * Create an instance of {@link TParallel }
     */
    public TParallel createTParallel() {
        return new TParallel();
    }

    /**
     * Create an instance of {@link TDeadline }
     */
    public TDeadline createTDeadline() {
        return new TDeadline();
    }

    /**
     * Create an instance of {@link TPresentationParameters }
     */
    public TPresentationParameters createTPresentationParameters() {
        return new TPresentationParameters();
    }

    /**
     * Create an instance of {@link TArgument }
     */
    public TArgument createTArgument() {
        return new TArgument();
    }

    /**
     * Create an instance of {@link TMessageChoice }
     */
    public TMessageChoice createTMessageChoice() {
        return new TMessageChoice();
    }

    /**
     * Create an instance of {@link TDelegation }
     */
    public TDelegation createTDelegation() {
        return new TDelegation();
    }

    /**
     * Create an instance of {@link TLocalTask }
     */
    public TLocalTask createTLocalTask() {
        return new TLocalTask();
    }

    /**
     * Create an instance of {@link TBooleanExpr }
     */
    public TBooleanExpr createTBooleanExpr() {
        return new TBooleanExpr();
    }

    /**
     * Create an instance of {@link TEscalation }
     */
    public TEscalation createTEscalation() {
        return new TEscalation();
    }

    /**
     * Create an instance of {@link TDefaultCompletion }
     */
    public TDefaultCompletion createTDefaultCompletion() {
        return new TDefaultCompletion();
    }

    /**
     * Create an instance of {@link TMessageDisplay }
     */
    public TMessageDisplay createTMessageDisplay() {
        return new TMessageDisplay();
    }

    /**
     * Create an instance of {@link TCompletionBehavior }
     */
    public TCompletionBehavior createTCompletionBehavior() {
        return new TCompletionBehavior();
    }

    /**
     * Create an instance of {@link TLiteral }
     */
    public TLiteral createTLiteral() {
        return new TLiteral();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPeopleAssignments }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "peopleAssignments")
    public JAXBElement<TPeopleAssignments> createPeopleAssignments(TPeopleAssignments value) {
        return new JAXBElement<TPeopleAssignments>(_PeopleAssignments_QNAME, TPeopleAssignments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TImport }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "import")
    public JAXBElement<TImport> createImport(TImport value) {
        return new JAXBElement<TImport>(_Import_QNAME, TImport.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNotification }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "notification")
    public JAXBElement<TNotification> createNotification(TNotification value) {
        return new JAXBElement<TNotification>(_Notification_QNAME, TNotification.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THumanInteractions }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "humanInteractions")
    public JAXBElement<THumanInteractions> createHumanInteractions(THumanInteractions value) {
        return new JAXBElement<THumanInteractions>(_HumanInteractions_QNAME, THumanInteractions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPriorityExpr }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "priority")
    public JAXBElement<TPriorityExpr> createPriority(TPriorityExpr value) {
        return new JAXBElement<TPriorityExpr>(_Priority_QNAME, TPriorityExpr.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRoleAssignment }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "taskInitiator", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRoleAssignment> createTaskInitiator(TGenericHumanRoleAssignment value) {
        return new JAXBElement<TGenericHumanRoleAssignment>(_TaskInitiator_QNAME, TGenericHumanRoleAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNotifications }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "notifications")
    public JAXBElement<TNotifications> createNotifications(TNotifications value) {
        return new JAXBElement<TNotifications>(_Notifications_QNAME, TNotifications.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRoleAssignmentBase }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "genericHumanRole")
    public JAXBElement<TGenericHumanRoleAssignmentBase> createGenericHumanRole(TGenericHumanRoleAssignmentBase value) {
        return new JAXBElement<TGenericHumanRoleAssignmentBase>(_GenericHumanRole_QNAME, TGenericHumanRoleAssignmentBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTasks }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "tasks")
    public JAXBElement<TTasks> createTasks(TTasks value) {
        return new JAXBElement<TTasks>(_Tasks_QNAME, TTasks.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPotentialOwnerAssignment }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "potentialOwners", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TPotentialOwnerAssignment> createPotentialOwners(TPotentialOwnerAssignment value) {
        return new JAXBElement<TPotentialOwnerAssignment>(_PotentialOwners_QNAME, TPotentialOwnerAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRoleAssignment }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "businessAdministrators", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRoleAssignment> createBusinessAdministrators(TGenericHumanRoleAssignment value) {
        return new JAXBElement<TGenericHumanRoleAssignment>(_BusinessAdministrators_QNAME, TGenericHumanRoleAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLeanTask }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "leanTask")
    public JAXBElement<TLeanTask> createLeanTask(TLeanTask value) {
        return new JAXBElement<TLeanTask>(_LeanTask_QNAME, TLeanTask.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLogicalPeopleGroups }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "logicalPeopleGroups")
    public JAXBElement<TLogicalPeopleGroups> createLogicalPeopleGroups(TLogicalPeopleGroups value) {
        return new JAXBElement<TLogicalPeopleGroups>(_LogicalPeopleGroups_QNAME, TLogicalPeopleGroups.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRoleAssignment }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "excludedOwners", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRoleAssignment> createExcludedOwners(TGenericHumanRoleAssignment value) {
        return new JAXBElement<TGenericHumanRoleAssignment>(_ExcludedOwners_QNAME, TGenericHumanRoleAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTask }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "task")
    public JAXBElement<TTask> createTask(TTask value) {
        return new JAXBElement<TTask>(_Task_QNAME, TTask.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRoleAssignment }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "taskStakeholders", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRoleAssignment> createTaskStakeholders(TGenericHumanRoleAssignment value) {
        return new JAXBElement<TGenericHumanRoleAssignment>(_TaskStakeholders_QNAME, TGenericHumanRoleAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRoleAssignment }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "recipients", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRoleAssignment> createRecipients(TGenericHumanRoleAssignment value) {
        return new JAXBElement<TGenericHumanRoleAssignment>(_Recipients_QNAME, TGenericHumanRoleAssignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDocumentation }{@code >}}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", name = "documentation", scope = TExtensibleMixedContentElements.class)
    public JAXBElement<TDocumentation> createTExtensibleMixedContentElementsDocumentation(TDocumentation value) {
        return new JAXBElement<TDocumentation>(_TExtensibleMixedContentElementsDocumentation_QNAME, TDocumentation.class, TExtensibleMixedContentElements.class, value);
    }

}
