/*
 * Copyright 2012 Bangkok Project Team, GRIDSOLUT GmbH + Co.KG, and
 * University of Stuttgart (Institute of Architecture of Application Systems)
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.16 at 09:35:20 PM CEST 
//


package org.oasis_open.docs.ns.bpel4people.ws_humantask._200803;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPresentationElements complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="tPresentationElements">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="presentationParameters" type="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tPresentationParameters" minOccurs="0"/>
 *         &lt;element name="subject" type="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tDescription" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPresentationElements", propOrder = {
        "name",
        "presentationParameters",
        "subject",
        "description"
})
public class TPresentationElements
        extends TExtensibleElements {

    protected List<TText> name;
    protected TPresentationParameters presentationParameters;
    protected List<TText> subject;
    protected List<TDescription> description;

    /**
     * Gets the value of the name property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link TText }
     */
    public List<TText> getName() {
        if (name == null) {
            name = new ArrayList<TText>();
        }
        return this.name;
    }

    /**
     * Gets the value of the presentationParameters property.
     *
     * @return possible object is
     *         {@link TPresentationParameters }
     */
    public TPresentationParameters getPresentationParameters() {
        return presentationParameters;
    }

    /**
     * Sets the value of the presentationParameters property.
     *
     * @param value allowed object is
     *              {@link TPresentationParameters }
     */
    public void setPresentationParameters(TPresentationParameters value) {
        this.presentationParameters = value;
    }

    /**
     * Gets the value of the subject property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link TText }
     */
    public List<TText> getSubject() {
        if (subject == null) {
            subject = new ArrayList<TText>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the description property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link TDescription }
     */
    public List<TDescription> getDescription() {
        if (description == null) {
            description = new ArrayList<TDescription>();
        }
        return this.description;
    }

}
